-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "listings_dupe" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"zpid" text NOT NULL,
	"detail_url" text,
	"status_type" varchar(50),
	"status_text" varchar(100),
	"address" text,
	"address_street" text,
	"address_city" varchar(100),
	"address_state" varchar(2),
	"address_zipcode" varchar(10),
	"price" numeric(12, 2),
	"beds" numeric(3, 1),
	"baths" numeric(3, 1),
	"area" integer,
	"is_featured" boolean DEFAULT false,
	"is_showcase" boolean DEFAULT false,
	"latitude" numeric(10, 8),
	"longitude" numeric(11, 8),
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"is_live" boolean DEFAULT true,
	"has_extra_features" boolean DEFAULT false,
	"coordinates" geometry(Point,4326),
	"description" text,
	"year_built" integer,
	"parking_spaces" integer,
	"has_air_conditioning" boolean,
	"has_heating" boolean,
	"has_dishwasher" boolean,
	"has_washer_dryer" boolean,
	"pets_allowed" boolean,
	"amenities" jsonb,
	"pet_policy" jsonb,
	"broker" text,
	"tax_assessment" numeric,
	"tax_annual_amount" numeric,
	"zestimate" numeric,
	"price_per_square_foot" numeric,
	"favorite_count" numeric,
	"page_views" numeric,
	"days_on_market" numeric,
	"price_change" numeric,
	"price_change_date" bigint,
	"lot_size" numeric,
	"agent_info" text,
	"property_type" text,
	"has_details" boolean,
	CONSTRAINT "listings_dupe_zpid_key" UNIQUE("zpid"),
	CONSTRAINT "listings_dupe_zpid_key1" UNIQUE("zpid")
);
--> statement-breakpoint
CREATE TABLE "places" (
	"id" bigint PRIMARY KEY NOT NULL,
	"category" text,
	"name" text,
	"brand" text,
	"lon" double precision,
	"lat" double precision,
	"check_date" text,
	"addr:city" text,
	"addr:housenumber" text,
	"addr:postcode" bigint,
	"addr:street" text,
	"subcategory" text,
	"addr:state" text,
	"coordinates" "geography"
);
--> statement-breakpoint
ALTER TABLE "places" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "listings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"zpid" text NOT NULL,
	"detail_url" text,
	"status_type" varchar(50),
	"status_text" varchar(100),
	"address" text,
	"address_street" text,
	"address_city" varchar(100),
	"address_state" varchar(2),
	"address_zipcode" varchar(10),
	"price" numeric(12, 2),
	"beds" numeric(3, 1),
	"baths" numeric(3, 1),
	"area" integer,
	"is_featured" boolean DEFAULT false,
	"is_showcase" boolean DEFAULT false,
	"latitude" numeric(10, 8),
	"longitude" numeric(11, 8),
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"is_live" boolean DEFAULT true,
	"has_extra_features" boolean DEFAULT false,
	"coordinates" geometry(Point,4326),
	"description" text,
	"year_built" integer,
	"parking_spaces" integer,
	"has_air_conditioning" boolean,
	"has_heating" boolean,
	"has_dishwasher" boolean,
	"has_washer_dryer" boolean,
	"pets_allowed" boolean,
	"amenities" jsonb,
	"pet_policy" jsonb,
	"has_details" boolean DEFAULT false NOT NULL,
	"raw_json_details" jsonb,
	"crime_score" double precision,
	"traffic_score" double precision,
	"overall_score" double precision,
	CONSTRAINT "listings_zpid_unique" UNIQUE("zpid"),
	CONSTRAINT "listings_zpid_key" UNIQUE("zpid")
);
--> statement-breakpoint
ALTER TABLE "listings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "cached_queries" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cached_queries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"query" text NOT NULL,
	"result" jsonb NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cached_queries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "listing_images" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"zpid" text NOT NULL,
	"image_url" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "listing_images_zpid_image_url_key" UNIQUE("zpid","image_url")
);
--> statement-breakpoint
ALTER TABLE "listing_images" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "spatial_ref_sys" (
	"srid" integer NOT NULL,
	"auth_name" varchar(256),
	"auth_srid" integer,
	"srtext" varchar(2048),
	"proj4text" varchar(2048),
	CONSTRAINT "spatial_ref_sys_srid_check" CHECK ((srid > 0) AND (srid <= 998999))
);
--> statement-breakpoint
CREATE TABLE "crime" (
	"analysis_neighborhood" text,
	"cad_number" text,
	"cnn" bigint,
	"data_as_of" timestamp with time zone,
	"data_loaded_at" timestamp with time zone,
	"filed_online" text,
	"incident_category" text,
	"incident_code" bigint,
	"incident_date" timestamp with time zone,
	"incident_datetime" timestamp with time zone,
	"incident_day_of_week" text,
	"incident_description" text,
	"incident_id" bigint,
	"incident_number" bigint,
	"incident_subcategory" text,
	"incident_time" text,
	"incident_year" bigint,
	"intersection" text,
	"latitude" double precision,
	"longitude" double precision,
	"point" text,
	"police_district" text,
	"report_datetime" timestamp with time zone,
	"report_type_code" text,
	"report_type_description" text,
	"resolution" text,
	"row_id" bigint PRIMARY KEY NOT NULL,
	"supervisor_district" bigint,
	"supervisor_district_2012" bigint,
	"geom" geometry(Point,4326)
);
--> statement-breakpoint
ALTER TABLE "crime" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "tours" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tours_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" uuid NOT NULL,
	"listing_id" uuid NOT NULL,
	"message" text
);
--> statement-breakpoint
ALTER TABLE "tours" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "profiles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"first_name" text,
	"last_name" text,
	"avatar_url" text,
	"full_name" text,
	"updated_at" timestamp with time zone,
	CONSTRAINT "profiles_id_key" UNIQUE("id")
);
--> statement-breakpoint
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "traffic" (
	"classcode" text,
	"cnn" bigint,
	"street" text,
	"geometry" jsonb,
	"geom" geometry(Geometry,4326)
);
--> statement-breakpoint
ALTER TABLE "traffic" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "grocery_stores" (
	"ID" bigint,
	"Store" text,
	"Address" text,
	"Latitude" double precision,
	"Longitude" double precision
);
--> statement-breakpoint
CREATE TABLE "old_bad_neighborhoods (To be deleted)" (
	"nhood" text,
	"the_geom" geometry(MultiPolygon,4326)
);
--> statement-breakpoint
CREATE TABLE "scores" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "scores_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"latitude" double precision NOT NULL,
	"longitude" double precision NOT NULL,
	"intersection_name" text,
	"cnn" text,
	"crime_score" double precision,
	"traffic_score" double precision,
	"geom" geometry(Point,4326),
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "scores_latitude_longitude_key" UNIQUE("latitude","longitude")
);
--> statement-breakpoint
CREATE TABLE "neighborhoods" (
	"the_geom" geometry(MultiPolygon,4326),
	"link" text,
	"name" text
);
--> statement-breakpoint
ALTER TABLE "neighborhoods" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "contact_submissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contact_submissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text,
	"email" text,
	"message" text
);
--> statement-breakpoint
ALTER TABLE "contact_submissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "listings_images_dupe" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"zpid" text NOT NULL,
	"image_url" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "listings_images_dupe_zpid_image_url_key" UNIQUE("zpid","image_url")
);
--> statement-breakpoint
CREATE TABLE "listing_images_dupe" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"zpid" text NOT NULL,
	"image_url" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "listing_images_dupe_zpid_image_url_key" UNIQUE("zpid","image_url")
);
--> statement-breakpoint
CREATE TABLE "favorite_listings" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "favorite_listings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" uuid NOT NULL,
	"listing_id" uuid NOT NULL,
	CONSTRAINT "unique_user_listing" UNIQUE("user_id","listing_id")
);
--> statement-breakpoint
ALTER TABLE "favorite_listings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "properties" (
	"id" serial PRIMARY KEY NOT NULL,
	"zpid" bigint NOT NULL,
	"street_address" text,
	"city" text,
	"state" text,
	"zipcode" text,
	"neighborhood" text,
	"home_status" text,
	"price" numeric,
	"bedrooms" numeric,
	"bathrooms" numeric,
	"property_type_dimension" text,
	"is_listed_by_owner" boolean,
	"days_on_zillow" integer,
	"description" text,
	"address" jsonb,
	"rental_available_tour_times" jsonb,
	"rental_applications_accepted_type" text,
	"home_insights" jsonb,
	"price_history" jsonb,
	"reso_facts" jsonb,
	"attribution_info" jsonb,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "properties_zpid_key" UNIQUE("zpid")
);
--> statement-breakpoint
ALTER TABLE "properties" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "listing_images" ADD CONSTRAINT "listing_images_zpid_fkey" FOREIGN KEY ("zpid") REFERENCES "public"."listings"("zpid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tours" ADD CONSTRAINT "tours_listing_id_fkey" FOREIGN KEY ("listing_id") REFERENCES "public"."listings"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tours" ADD CONSTRAINT "tours_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "favorite_listings" ADD CONSTRAINT "favorite_listings_listing_id_fkey" FOREIGN KEY ("listing_id") REFERENCES "public"."listings"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "favorite_listings" ADD CONSTRAINT "favorite_listings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "listings_dupe_coordinates_idx" ON "listings_dupe" USING gist ("coordinates" gist_geometry_ops_2d);--> statement-breakpoint
CREATE INDEX "listings_dupe_zpid_idx" ON "listings_dupe" USING btree ("zpid" text_ops);--> statement-breakpoint
CREATE INDEX "places_coordinates_idx" ON "places" USING gist ("coordinates" gist_geography_ops);--> statement-breakpoint
CREATE INDEX "places_name_idx" ON "places" USING btree ("name" text_ops);--> statement-breakpoint
CREATE INDEX "idx_listings_coordinates" ON "listings" USING gist ("coordinates" gist_geometry_ops_2d);--> statement-breakpoint
CREATE INDEX "idx_listings_zpid" ON "listings" USING btree ("zpid" text_ops);--> statement-breakpoint
CREATE INDEX "listings_baths_idx" ON "listings" USING btree ("baths" numeric_ops);--> statement-breakpoint
CREATE INDEX "listings_beds_idx" ON "listings" USING btree ("beds" numeric_ops);--> statement-breakpoint
CREATE INDEX "listings_coordinates_idx" ON "listings" USING gist ("coordinates" gist_geometry_ops_2d);--> statement-breakpoint
CREATE INDEX "listings_latitude_longitude_idx" ON "listings" USING btree ("latitude" numeric_ops,"longitude" numeric_ops);--> statement-breakpoint
CREATE INDEX "listings_price_idx" ON "listings" USING btree ("price" numeric_ops);--> statement-breakpoint
CREATE INDEX "idx_listing_images_zpid" ON "listing_images" USING btree ("zpid" text_ops);--> statement-breakpoint
CREATE INDEX "idx_crime_geom" ON "crime" USING gist ("geom" gist_geometry_ops_2d);--> statement-breakpoint
CREATE INDEX "idx_traffic_geom" ON "traffic" USING gist ("geom" gist_geometry_ops_2d);--> statement-breakpoint
CREATE INDEX "idx_scores_geom" ON "scores" USING gist ("geom" gist_geometry_ops_2d);--> statement-breakpoint
CREATE INDEX "idx_scores_lat_lng" ON "scores" USING btree ("latitude" float8_ops,"longitude" float8_ops);--> statement-breakpoint
CREATE INDEX "listings_images_dupe_zpid_idx" ON "listings_images_dupe" USING btree ("zpid" text_ops);--> statement-breakpoint
CREATE INDEX "listing_images_dupe_zpid_idx" ON "listing_images_dupe" USING btree ("zpid" text_ops);--> statement-breakpoint
CREATE INDEX "idx_properties_description" ON "properties" USING gin (to_tsvector('english'::regconfig, description) tsvector_ops);--> statement-breakpoint
CREATE INDEX "idx_properties_zpid" ON "properties" USING btree ("zpid" int8_ops);--> statement-breakpoint
CREATE VIEW "public"."geography_columns" AS (SELECT current_database() AS f_table_catalog, n.nspname AS f_table_schema, c.relname AS f_table_name, a.attname AS f_geography_column, postgis_typmod_dims(a.atttypmod) AS coord_dimension, postgis_typmod_srid(a.atttypmod) AS srid, postgis_typmod_type(a.atttypmod) AS type FROM pg_class c, pg_attribute a, pg_type t, pg_namespace n WHERE t.typname = 'geography'::name AND a.attisdropped = false AND a.atttypid = t.oid AND a.attrelid = c.oid AND c.relnamespace = n.oid AND (c.relkind = ANY (ARRAY['r'::"char", 'v'::"char", 'm'::"char", 'f'::"char", 'p'::"char"])) AND NOT pg_is_other_temp_schema(c.relnamespace) AND has_table_privilege(c.oid, 'SELECT'::text));--> statement-breakpoint
CREATE VIEW "public"."geometry_columns" AS (SELECT current_database()::character varying(256) AS f_table_catalog, n.nspname AS f_table_schema, c.relname AS f_table_name, a.attname AS f_geometry_column, COALESCE(postgis_typmod_dims(a.atttypmod), sn.ndims, 2) AS coord_dimension, COALESCE(NULLIF(postgis_typmod_srid(a.atttypmod), 0), sr.srid, 0) AS srid, replace(replace(COALESCE(NULLIF(upper(postgis_typmod_type(a.atttypmod)), 'GEOMETRY'::text), st.type, 'GEOMETRY'::text), 'ZM'::text, ''::text), 'Z'::text, ''::text)::character varying(30) AS type FROM pg_class c JOIN pg_attribute a ON a.attrelid = c.oid AND NOT a.attisdropped JOIN pg_namespace n ON c.relnamespace = n.oid JOIN pg_type t ON a.atttypid = t.oid LEFT JOIN ( SELECT s.connamespace, s.conrelid, s.conkey, replace(split_part(s.consrc, ''''::text, 2), ')'::text, ''::text) AS type FROM ( SELECT pg_constraint.connamespace, pg_constraint.conrelid, pg_constraint.conkey, pg_get_constraintdef(pg_constraint.oid) AS consrc FROM pg_constraint) s WHERE s.consrc ~~* '%geometrytype(% = %'::text) st ON st.connamespace = n.oid AND st.conrelid = c.oid AND (a.attnum = ANY (st.conkey)) LEFT JOIN ( SELECT s.connamespace, s.conrelid, s.conkey, replace(split_part(s.consrc, ' = '::text, 2), ')'::text, ''::text)::integer AS ndims FROM ( SELECT pg_constraint.connamespace, pg_constraint.conrelid, pg_constraint.conkey, pg_get_constraintdef(pg_constraint.oid) AS consrc FROM pg_constraint) s WHERE s.consrc ~~* '%ndims(% = %'::text) sn ON sn.connamespace = n.oid AND sn.conrelid = c.oid AND (a.attnum = ANY (sn.conkey)) LEFT JOIN ( SELECT s.connamespace, s.conrelid, s.conkey, replace(replace(split_part(s.consrc, ' = '::text, 2), ')'::text, ''::text), '('::text, ''::text)::integer AS srid FROM ( SELECT pg_constraint.connamespace, pg_constraint.conrelid, pg_constraint.conkey, pg_get_constraintdef(pg_constraint.oid) AS consrc FROM pg_constraint) s WHERE s.consrc ~~* '%srid(% = %'::text) sr ON sr.connamespace = n.oid AND sr.conrelid = c.oid AND (a.attnum = ANY (sr.conkey)) WHERE (c.relkind = ANY (ARRAY['r'::"char", 'v'::"char", 'm'::"char", 'f'::"char", 'p'::"char"])) AND NOT c.relname = 'raster_columns'::name AND t.typname = 'geometry'::name AND NOT pg_is_other_temp_schema(c.relnamespace) AND has_table_privilege(c.oid, 'SELECT'::text));--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "places" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "listings" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "listing_images" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable All for users based on user_id" ON "tours" AS PERMISSIVE FOR ALL TO public USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));--> statement-breakpoint
CREATE POLICY "Enable insert for users based on id" ON "profiles" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((( SELECT auth.uid() AS uid) = id));--> statement-breakpoint
CREATE POLICY "Enable update for users based on id" ON "profiles" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Enable users to view their own data only" ON "profiles" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "neighborhoods" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable all commands for service role" ON "contact_submissions" AS PERMISSIVE FOR ALL TO "service_role" USING (true);--> statement-breakpoint
CREATE POLICY "Enable all permissions for users based on user_id" ON "favorite_listings" AS PERMISSIVE FOR ALL TO public USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
*/